spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/CWDB
    username: whynot
    password: whynotishe
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.mail.ru
    port: 465
    username: whynotpc@mail.ru
    password: b6ENcxjZDw6ASaGw95mM
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
logging:
  level:
    org.apache.coyote.http11.Http11Processor: TRACE

